kafka:
  bootstrap-servers: localhost:9092
  auto-reset: earliest
  consumer:
    groupId: test-group
    topics: test-38,test-39
  responses:
    lineeMobili.responseCambioNumero.v1: test-response-1
    lineeMobili.responseBloccoSbloccoNumero.v1: test-response-2
    lineeMobili.responseCancellaUtenza.v1: test-response-3
    lineeMobili.responseCambioCarta.v1: test-response-4
    lineeMobili.responseCreaUtenza.v1: test-response-5
    lineeMobili.responseAttivazioneUtenza.v1 : test-response-6
    lineeMobili.responseCambioUtenza.v1: test-response-7
    

trcs:
  gateway:
    services:
      gino-provisioning: 
         address: http://localhost:8095/gateway/provisioning
         timeout-connection: 30000
         timeout-read: 3000
      gino-recharge:
         address: http://localhost:8090/gateway/recharge
         timeout-connection: 30000
         timeout-read: 3000
      opsc-provisionig: 
         address: http://localhost:8095/gateway/opsc/provisioning
         timeout-connection: 30000
         timeout-read: 3000
     
      