kafka:
  bootstrap-servers: localhost:9092
  #bootstrap-servers: pkc-lzoyy.europe-west6.gcp.confluent.cloud:9092
  #security.protocol: SASL_SSL
  #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='LTVL5DA226U3NK6L'   password='598mOQXYS9vtO5ZgeXr1uYU19bRpTl4F7xhbnZ3MbpN3+tLnOTAXUwCuXZh5ZIgL';
  #sasl.mechanism: PLAIN
  # Required for correctness in Apache Kafka clients prior to 2.6
  #client.dns.lookup: use_all_dns_ips
  # Best practice for Kafka producer to prevent data loss
  #acks: all
  # Required connection configs for Confluent Cloud Schema Registry
  #schema.registry.url: https://{{ SR_ENDPOINT }}
  #basic.auth.credentials.source: USER_INFO
  #basic.auth.user.info: "{{ SR_API_KEY }}:{{ SR_API_SECRET }}"
  auto-reset: earliest
  consumer:
    groupId: demo-consumer-1
    topics: test2
  responses:
    lineeMobili.responseCambioNumero.v1: test-response-1
    lineeMobili.responseBloccoSbloccoNumero.v1: test-response-2
    lineeMobili.responseCancellaUtenza.v1: test-response-3
    lineeMobili.responseCambioCarta.v1: test-response-4
    lineeMobili.responseCreaUtenza.v1: test-response-5
    lineeMobili.responseAttivazioneUtenza.v1 : test-response-6
    lineeMobili.responseCambioUtenza.v1: test-response-7
    

trcs:
  gateway:
    services:
      gino-provisioning: 
         address: http://localhost:8095/gateway/provisioning
         timeout-connection: 300000
         timeout-read: 300000
      gino-recharge:
         address: http://localhost:8090/gateway/recharge
         timeout-connection: 300000
         timeout-read: 300000
      opsc-provisionig: 
         address: http://localhost:8095/gateway/opsc/provisioning
         timeout-connection: 30000
         timeout-read: 300000
     
      