kafka:
  bootstrap-servers: localhost:9092
  auto-reset: earliest
  consumer:
    groupId: test-group
    topics: test-22,test-23
  responses:
    lineeMobili.responseCambioNumero.v1: test-response-1
    lineeMobili.responseBloccoSbloccoNumero.v1: test-response-2


trcs:
  gateway:
    services:
      opsc-provisionig: http://localhost:8095/gateway/opsc/provisioning